[project]
name = "affinity-project"
version = "0.1.0"
description = "Predict the Binding Affinity of a Target Protein to it's mutated target DNA"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kedro>=0.19.12",
    "kedro-viz>=11.0.1",
]
